# Generated by Django 4.1.7 on 2023-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streetlight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("salary", models.FloatField()),
                ("email", models.TextField()),
                ("city", models.TextField()),
                ("requirement", models.TextField()),
                ("department", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                ("hunting_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("CV", models.TextField()),
                ("ps", models.TextField()),
                ("name", models.TextField()),
                ("birth_day", models.TextField()),
                ("submit_time", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.TextField()),
                ("sex", models.TextField()),
                ("tel", models.TextField()),
                ("email", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
    ]
